spring:
  datasource:
    url: jdbc:mysql://localhost:3306/generate?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: dev
    password: dev123456
    initialSize: 5
    maxActive: 50
    minIdle: 10
