spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/generator?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    initialSize: 5
    maxActive: 50
    minIdle: 10
