spring:
  datasource:
    url: jdbc:mysql://o2omysql.m.aomygod.api:3306/o2o_college?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: dev
    password: dev123456
    initialSize: 5
    maxActive: 50
    minIdle: 10
